version: '3.8'
services:
  frontend:
    build: ./frontend
    depends_on:
      - backend
    volumes:
      - ./frontend:/app/frontend
    networks:
      - shop

  backend:
    build: ./backend
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=root
      - DB_NAME=shop
      - DB_PORT=5432
    depends_on:
      - db
    networks:
      - shop

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=shop
    volumes:
      - ./db/data:/var/lib/postgresql/data
    ports: 
      - "5432:5432" # debug only
    networks:
      - shop

  nginx:
    build: ./nginx
    ports:
      - "8088:80" 
    depends_on:
      - frontend
      - backend
    networks:
      - shop

networks:
  shop:
    driver: bridge
