version: '3.8'
services:
  frontend:
    build: ./frontend
    depends_on:
      - backend
    # remove volumes when it comes to product
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - shop

  backend:
    build: ./backend
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=root
      - DB_NAME=shop
    depends_on:
      - db
    networks:
      - shop

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=shop
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - shop

  nginx:
    build: ./nginx
    ports:
      - "8088:80" 
    depends_on:
      - frontend
      - backend
    networks:
      - shop

networks:
  shop:
    driver: bridge